# Generated by Django 5.0.3 on 2024-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_lesson_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_5',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
