# Generated by Django 5.0.3 on 2024-08-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_qestionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='qestionreport',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_report', to='exam.quiz'),
        ),
    ]
