# Generated by Django 5.0.3 on 2024-08-05 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_qestionreport_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='qestionreport',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qestionreport',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_report', to='exam.quiz'),
        ),
    ]
