# Generated by Django 5.0.3 on 2024-04-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_phone_number_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_quiz_maker',
            field=models.BooleanField(default=False),
        ),
    ]
