# Generated by Django 5.0.3 on 2024-06-11 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takingtest', '0008_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
