# Generated by Django 5.0.3 on 2024-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takingtest', '0009_alter_quizhistory_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizhistory',
            name='user_answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
